### ISSUE TITLE
Generate custom project file with XcodeGen on top of kiwix/apple

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple-custom#1]
We want to dynamically generate the Xcode project files with XcodeGen for custom projects as well, using the kiwix/apple repository as our base and build on top of it.

The kiwix/apple repository has been prepared to contain all the "base" settings for the Xcode project, that we inherit for the custom apps.

We are creating a new project file that is importing the "project.yml" from the kiwix/apple repo.
This way we are re-using the XcodeGen template from the kiwix/apple repo, and adding new custom targets.

This way all the base settings are still applicable, and we only customising the bare minimum, without any duplications.

The current setup is based on a similar info.json file as the Android one (see: kiwix/kiwix-android-custom), each contained in a "brand" folder. Currently we have 1 brand: "dwds".

What we need in each brand folder:
- an info.json file
- xcassets (these are mostly images and icons for the brand)

The rest of the process is automated to create the appropriate branded targets:
<img width="342" alt="Screenshot 2023-12-31 at 15 06 12" src="https://github.com/kiwix/kiwix-apple-custom/assets/6784320/580e50cf-0bee-4a5c-9811-fcbf8ac6f260">

**Comment by kelson42** [comment]
Fi
