### ISSUE TITLE
Trigger CD build, and set build version from GitHub tags

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple-custom#12]
The CD GitHub action should start from a published tag.
The tag should contain the folder name (brand name), the build number (the [PATCH] part of the version) as the [MAJOR].[MINOR] is based on the ZIM file date (see issue on versioning).
The tag should be validated, if it has the right format, and if the folder actually exists.
Eg. a valid tag should look like:
`dwds_03` out of which we have the `dwds` folder/brand to be built with the build number 3 (there are no zeros in semantic versioning).
Also it should be possible to extend the tag with a further optional part, such as:
`dwds_11_A1` or `dwds_11_test02` in order to be able to retry building or overriding builds with the same number, but having different tags.

**Comment by kelson42** [comment]
Fixes by [#13](https://github.com/kiwix/kiwix-apple-custom/pull/13) I guess
