### ISSUE TITLE
Custom Apps CD - per brand, set version from release tag

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple-custom#17]
We want to build and deliver custom apps via a manual trigger, similar to `kiwix/kiwix-android-custom`.
Assumptions:
- The build should be triggered by a release, with the appropriate tag (see below)
- On a single run only the apps of one brands should be built.
- The versioning should be inline with the ZIM file based approach described here: https://github.com/kiwix/apple/issues/559,
meaning we have the version [MAJOR].[MINOR].[PATCH] = YYYY.MM.build_number
- The `build_number` should be taken from the tag we create on the release
- In order to be able to create the same `build_number` twice (we might need to restart or overwrite the build), any additional parts can be appended to tags.
- Tags should be validated, and should come in the form: brandName_buildNumber(_optionalPart), where the brandName must be an existing folder (on the `main` branch), containing an `info.json` file.

**Comment by kelson42** [comment]
@BPerlakiH @rgaudin Maybe I got that wrong, but I though we agree that the whole version comes from the tag?!

**Comment by BPerlakiH** [comment]
@kelson42 I think we can change it to be the whole version. We can validate against the brand folder name and the URL / file name (ending) contained in the info.json.

**Comment by BPerlakiH** [comment]
I've

**Comment by BPerlakiH** [comment]
@kelson42 @rgaudin it has been implemented, and tested with this tag here: https://github.com/kiwix/kiwix-apple-custom/actions/runs/7514404208

**Comment by kelson42** [comment]
@BPerlakiH Good, but where is the code to review?

**Comment by BPerlakiH** [comment]
It has been merged into kiwix/kiwix-apple-custom main branch.
