### ISSUE TITLE
Nightly CI

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple-custom#48]
We had a rough CI implemented in on of our introduction PR but now we have nothing.

**Comment by kelson42** [comment]
@BPerlakiH I know this was not the priority but having seen the code in one of the PR, I have been surprised that we have nothing in `main` branch. I had even prepare https://dev.kiwix.org/apple/custom/test/wikipedia_en_ray_charles_maxi_2023-12.zim to use for a CI doing a simple compilation test. Do I have got this wrong? Can we reintroduce it?

**Comment by BPerlakiH** [comment]
@kelson42 I think we can put this together from the existing / working parts.
My feeling is that it would be essential to summarise **what we want to check in this integration process.**
The way I see it, is that we have python code in this repository and some tests to them, so it would be nice **to run those python tests** as part of this process.
In terms of the apps itself, we have a couple of options either: 
- we try to detect which folders (new folders) are changed and try to build those brands, 
- or build all the brands, but do not upload them anywhere. Securing this way that the change introduced is OK.

What do you think ?

**Comment by rgaudin** [comment]
I agree:

- run python tests
- build what changed (no upload).

Regarding detection, we had it [there](https://github.com/offspot/container-images/blob/7407ff7ed53c060b65412c715adce7974845c55f/.github/workflows/docker.yaml).

It's a detail but I prefer having a dedicated workflow for each App/brand. This way, we get a properly named, dedicated action per brand and easily see what triggered and identify if it failed. Only drawback is it requires duplicating a workflow file when we add a new brand.

This can be considered an optimization and is less important so do as you prefer for now ; what's important is building in the CI

**Comment by kelson42** [comment]
@BPerlakiH @rgaudin You are already far further as what I foreaee.

To start, triggered like on other repos, a CI dedicated worflow which just:
* compile a fake app
* run any dedicated test alredy made in this repo.

BTW, at this stage, I'm not in favour, of having app dedicated workflows. We might open an other ticket asking and discussing how we could do a smarter CI: compile modified app, verfy that all the prerequisites are OK, ...

**Comment by kelson42** [comment]
After discussion, this check to verify that this repo continues to compile fine against `kiwix/apple` might better run jun once per night with the data of a test/fake app.

**Comment by BPerlakiH** [comment]
Re-opening: We still need the part to run the python tests.
