### ISSUE TITLE
Wikimed logo should have more border

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple-custom#50]
<img width="249" alt="image" src="https://github.com/kiwix/kiwix-apple-custom/assets/1029718/3d2d37b7-f6fa-414c-a005-a9f19538a4f3">

currently the logo stick very much to the border, the lack of margin is not nice.

**Comment by BPerlakiH** [comment]
Fixing in https://github.com/kiwix/kiwix-apple-custom/tree/50-wikimed-logo-should-have-more-border
