### ISSUE TITLE
Update custom apps to be compatible with new Launch sequence

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple-custom#72]
After the completion of: https://github.com/kiwix/kiwix-apple/issues/975

We need to make sure that the custom apps:
- have their launch screen storyboards updated, to place the logo in the right place
- include data about the original image size of the logo used on the launch screen

We need to double check their loading sequence.

**Comment by kelson42** [comment]
@BPerlakiH Should be treated in prio
